config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'city/input'
root 'city#input'
post "city/results" => "city#results"

get 'city/results'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def results
    @city = params[:city] || "miami"

    weather = HTTParty.get("http://api.openweathermap.org/data/2.5/weather?q=#{@city}&appid=c38d29204353577f04f9a8b861e3c70e")

    weather = JSON.parse(weather.body)
    if weather["cod"] === "502"
      @is_not_found = true
      @not_found = weather["message"]
    else
      @weather_description = weather["weather"][0]["description"]
      weather_input = @weather_description.gsub!(' ','+')
      @weather_description = @weather_description.gsub!('+',' ').upcase

      weather_temp_current = weather["main"]["temp"] - 273.15
      @weather_temp_current = weather_temp_current.to_i
      # weather_temp_min = weather["main"]["temp_min"] - 273.15
      # weather_temp_max = weather["main"]["temp_max"] - 273.15
      @country_code = weather["sys"]["country"]


      giphy = HTTParty.get("http://api.giphy.com/v1/gifs/search?q=#{weather_input}&api_key=dc6zaTOxFJmzC")
      giphy = JSON.parse(giphy.body)
      # A) Esta opcion da un random - "sample"- de los gifs
      # giphy = giphy['data'].sample
      # giphy = giphy['images']['original']['url']
      #B) Esta opcion esta asociada siempre al 1er Gif (posicion 0)
      @giphy = giphy['data'][0]['images']['original']['url']
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/views/city/input.html.erb
<h1 class="lead weather-title level2"><strong>Funny Weather</strong></h1>
<%= form_tag city_results_path, method: "post", class: 'col-md-6 text-center level2' do %>
    <div class="form-group">
      <%= label_tag :city, 'City', class: "lead no-margin level2" %><br>
      <%= text_field_tag :city , '', class: "form-control level2" %>
    </div>


    <%= submit_tag "Get Weather", class: 'btn btn-success btn-lg level2' %>
  </p>
<% end %>
<div id="video-background">
<%= video_tag "App_background.mp4", autoplay:true, height: "100%", width: "100%", loop: true%>
</div>

app/views/city/results.html.erb
<h1 class="lead text-center"><strong>The Funniest weather in the world!</strong></h1>
<div class="container-fluid center-container">
  <% if @is_not_found %>
    <div class="col-md-8" style="width: 100%;">
      <p class="lead text-center">
        <%= @not_found%>
      </p>
      <%= form_tag city_results_path, method: "post", class: ' col-md-offset-3 col-md-6 text-center text-center' do %>
          <div class="form-group">
            <%= label_tag :city, 'City', class: "lead no-margin"%><br>
            <%= text_field_tag :city , '', class: "form-control" %>
          </div>
          <%= submit_tag "Get Weather", class: 'btn btn-success btn-lg' %>
        </p>
      <% end %>
    </div>
    <% else %>
    <div class="col-md-12 flex-container">
      <div class="col-md-6">
        <div class="climate">
          <p class="weather-info">
            The current weather in
            <strong><%=@city.upcase%></strong> (<%= @country_code %>) is:
            <strong><%= @weather_temp_current %> °C </strong>
            and it looks like <span class="weather-desc"><%= @weather_description.humanize%></span>
          </p>

          <%= form_tag city_results_path, method: "post", class: 'col-md-6 text-center' do %>
              <div class="form-group">
                <%= label_tag :city, 'City', class: "lead no-margin"%><br>
                <%= text_field_tag :city , '', class: "form-control" %>
              </div>
              <%= submit_tag "Get Weather", class: 'btn btn-success btn-lg' %>
            </p>
          <% end %>

        </div>

      </div>
      <div class="col-md-6">
        <div class="gif_image">
          <img src="<%= @giphy %>" class='img-responsive img-thumbnail' alt="giphy" />
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Climate</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >

    <!-- Latest compiled and minified JavaScript -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>
  </head>

  <body class="<%= controller_name%> <%= controller.action_name%>">
    <%= yield %>
  </body>
</html>